#!/bin/csh -f

echo "clean up old files"
rm -rf csrc simv* *.fsdb

echo "mkdir ./results_simutop_CIMU"
mkdir ./results_simutop_CIMU

# Compile
echo "verilog compilation"
vcs  \
  -nc  \
  -full64  \
  -sverilog  \
 	./simu_top_SCCM.v \
	./SM.v \
  ./inputFIFO.v \
  ./outputFIFO.v \
  ./IO.v \
  ./inputFIFO_unit.v\
  ./CONTROLLER.v\
  ./SHIFTER.v\
  ./SIMDadd.v\
  ./SIMDshifter.v\
  ./FIFO_ASYN.v\
  ./SRAMCIMfinal.v\
  +lint=TFIPC-L  \
  -debug_access+all  \
  -l ./results_simutop_CIMU/vcs_simutop_CIMU.log  \
  
./simv  \
  -nc  \
  +COMPARE  \
  -l ./results_simutop_CIMU/simu_simutop_CIMU.log
  
mv ./vcs_simutop.fsdb ./results_simutop_CIMU/
    
