#!/bin/csh -f

echo "clean up old files"
rm -rf csrc simv* *.fsdb

echo "mkdir ./results_quantize"
mkdir ./results_simutop_quantize

# Compile
echo "verilog compilation"
vcs  \
  -nc  \
  -full64  \
  -sverilog  \
 	./simutop_quantize.v \
  ./quantize.v \
  ./quantize_6to4.v \
  ./quantize_add.v \
  +lint=TFIPC-L  \
  -debug_access+all  \
  -l ./results_simutop_quantize/vcs_simutop_quantize.log  \
  
./simv  \
  -nc  \
  +COMPARE  \
  -l ./results_simutop_quantize/simu_simutop_quantize.log
  
mv ./vcs_simutop.fsdb ./results_simutop_quantize/
    
